<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Referafriend
 * @copyright  Copyright (c) 2003-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if (Mage::helper('referafriend')->isInviteAllowed() && !Mage::helper('referafriend')->getExtDisabled()): ?>
<p class="raf-right"><button class="form-button-alt button" id="referafriend-button" type="button"><span><?php echo $this->__('Invite a friend') ?></span></button></p>
<script type="text/javascript">
<!--
document.observe('dom:loaded', function () { new Referafriend($('referafriend-button'), '<?php echo Mage::helper('referafriend')->getReferafriendUrl() ?>'); });
//-->
</script>
<?php endif ?>