<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.2.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
 
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
    <?php if (Mage::helper('awautorelated')->checkVersion('1.4')): ?>
        <div class="block block-related aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>"  style="background:transparent;border:none;width:450px">
            <div class="block-title" style="border-top:2px solid #666666;border-bottom:none;">
                <span style="font-size:24px;color:#111111;padding:12px 0px 4px 0px;margin:0;">Similar Products<?php //echo $this->htmlEscape($this->getData('name')) ?></span>
            </div>
            <div class="block-content aw-arp-block-content" style="background:transparent;border:none;width:450px">
            <?php else: ?>
                <div class="box base-mini mini-related-items aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>"  style="background:transparent">
                    <div class="head">
                        <h4><?php echo $this->htmlEscape($this->getData('name')) ?></h4>
                    </div>
                    <div class="content aw-arp-block-content"  style="background:transparent;border:none;width:450px">
                    <?php endif; ?>
                    <ul style="padding-top:16px;">
                        <?php foreach ($collection as $product) : ?>
                            <li class="aw-arp-item">
                                <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(109) ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" width="109" height="109" /></a>
                                <a class="aw-prod-name" href="<?php echo $abstractBlock->getProductUrl($product) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
								<a class="aw-more-info" href="<?php echo $abstractBlock->getProductUrl($product) ?>">More Info</a>
                                <?php //echo $abstractBlock->getPriceHtml($product, true, '-related') ?>
                              <!--  <?php if ($product->isSaleable()) : ?>
                                  <div class="aw-arp-addtocart">
                                    <p>
                                       <?php if(!$this->isLocationLink($product)): ?>
                                            <a class="link-cart" href="<?php echo $abstractBlock->getAddToCartUrl($product) ?>"><?php echo $this->__('Add to Cart') ?></a>
                                        <?php else : ?>
                                            <a class="link-cart" href="javascript:setLocation('<?php echo $abstractBlock->getAddToCartUrl($product) ?>');"><?php echo $this->__('Add to Cart') ?></a>                                            
                                        <?php endif; ?>                                       
                                    </p>
                               </div>
                                <?php else : ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif ?>
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $abstractBlock->getAddToWishlistUrl($product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif; ?>-->
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
