<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 3.2
 * @since        Class available since Release 1.0
 */
 if(!Mage::getSingleton('checkout/session')->getQuote()->isVirtual()):?>

<?php echo $this->getChildHtml('shipping_method');?>

<?php endif;?>

<?php echo $this->getChildHtml('payment');?>
