<?php

/**
 * Class Eway_Rapid31_Model_Field_Customer
 *
 * @method long getTokenCustomerID()
 * @method Eway_Rapid31_Model_Field_Customer setTokenCustomerID(long $value)
 * @method string getReference()
 * @method Eway_Rapid31_Model_Field_Customer setReference(string $value)
 * @method string getTitle()
 * @method Eway_Rapid31_Model_Field_Customer setTitle(string $value)
 * @method string getFirstName()
 * @method Eway_Rapid31_Model_Field_Customer setFirstName(string $value)
 * @method string getLastName()
 * @method Eway_Rapid31_Model_Field_Customer setLastName(string $value)
 * @method string getCompanyName()
 * @method Eway_Rapid31_Model_Field_Customer setCompanyName(string $value)
 * @method string getJobDescription()
 * @method Eway_Rapid31_Model_Field_Customer setJobDescription(string $value)
 * @method string getStreet1()
 * @method Eway_Rapid31_Model_Field_Customer setStreet1(string $value)
 * @method string getStreet2()
 * @method Eway_Rapid31_Model_Field_Customer setStreet2(string $value)
 * @method string getCity()
 * @method Eway_Rapid31_Model_Field_Customer setCity(string $value)
 * @method string getState()
 * @method Eway_Rapid31_Model_Field_Customer setState(string $value)
 * @method string getPostalCode()
 * @method Eway_Rapid31_Model_Field_Customer setPostalCode(string $value)
 * @method string getCountry()
 * @method Eway_Rapid31_Model_Field_Customer setCountry(string $value)
 * @method string getEmail()
 * @method Eway_Rapid31_Model_Field_Customer setEmail(string $value)
 * @method string getPhone()
 * @method Eway_Rapid31_Model_Field_Customer setPhone(string $value)
 * @method string getMobile()
 * @method Eway_Rapid31_Model_Field_Customer setMobile(string $value)
 * @method string getComments()
 * @method Eway_Rapid31_Model_Field_Customer setComments(string $value)
 * @method string getFax()
 * @method Eway_Rapid31_Model_Field_Customer setFax(string $value)
 * @method string getUrl()
 * @method Eway_Rapid31_Model_Field_Customer setUrl(string $value)
 * @method Eway_Rapid31_Model_Field_CardDetails getCardDetails()
 * @method Eway_Rapid31_Model_Field_Customer setCardDetails(Eway_Rapid31_Model_Field_CardDetails $value)
 * @method bool getIsActive()
 * @method Eway_Rapid31_Model_Field_Customer setIsActive(bool $value)
 */
class Eway_Rapid31_Model_Field_Customer extends Eway_Rapid31_Model_JsonSerializableAbstract
{
}