<?php $value =Mage::registry('formbuilder')->getData('field');?>
<?php $fieldvalue='';?>
<?php if(isset($value) && !empty($value)):?>
	<?php $id=$this->getId();?>
	<?php $fieldvalue=$value[$id];?>
<?php endif;?>


<select name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId()?>' class='<?php echo $this->getFieldClass()?>' style='<?php echo $this->getFieldStyle()?>'>
<option value=""><?php echo $this->__('--Please Select--');?></option>
<?php  foreach($this->getFieldOptions() as $option):?>
<?php $checked = false;
	 if($option["checked"]){
		$checked = 'selected';
	}
?>
<option value="<?php echo htmlspecialchars($option["label"])?>" <?php if(isset($fieldvalue) && !empty($fieldvalue)):?><?php if(htmlspecialchars($option["label"]) ==$fieldvalue ):?> selected="seleced" <?php endif;?><?php else:?><?php echo $checked?><?php endif;?>><?php echo $option['label']?></option>
<?php endforeach;?>
</select>