
<script type="text/javascript">

OptionTemplateFile = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
           <?php /* '<th class="type-sku">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('formbuilder')->__('Code')); ?> + '<span class="required"> *</span></th>' +*/?>
            '<th class="type-title">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('formbuilder')->__('Allowed File Extensions')); ?> + '</th>'+
            '<th class="">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('formbuilder')->__('Maximum Image Size')); ?> + '</th>' +
			'<th class=""><?php echo Mage::helper('formbuilder')->__('Class') ?> </th>'+
        '</tr>' +
        '<tr>' +
            <?php /*'<td><input type="text" class="input-text" name="product[options][{{fieldset}}][{{option_id}}][sku]" value="{{sku}}"></td>' +*/?>
            '<td><input class="input-text" type="text" name="product[options][{{fieldset}}][{{option_id}}][file_extension]" value="{{file_extension}}"></td>' +
            '<td class="type-last" nowrap><input class="input-text" type="text" name="product[options][{{fieldset}}][{{option_id}}][image_size_x]" value="{{image_size_x}}">' +
                <?php echo $this->helper('core')->jsonEncode(Mage::helper('formbuilder')->__('x')) ?> +
                '<input class="input-text" type="text" name="product[options][{{fieldset}}][{{option_id}}][image_size_y]" value="{{image_size_y}}">' +
                 <?php echo $this->helper('core')->jsonEncode(Mage::helper('formbuilder')->__('px.')) ?> +
            '<br/>' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('leave blank if its not an image')) ?> + '</td>' +
			'<td class=""><input type="text" class="input-text" name="product[options][{{fieldset}}][{{option_id}}][class]" value="{{class}}"></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_file')) {
    $('option_panel_type_file').remove();
}

</script>
