<script type="text/javascript">
//<![CDATA[
OptionTemplateText = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
			'<th class=""><?php echo Mage::helper('formbuilder')->__('Class') ?> </th>'+
        '</tr>'+
        '<tr>'+
			'<td class=""><input type="text" class="input-text" name="product[options][{{fieldset}}][{{option_id}}][class]" value="{{class}}"></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_text')) {
    $('option_panel_type_text').remove();
}
//]]>
</script>
