<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @authors    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php
    $_productCollection=$this->getFeaturedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_coreHelper = $this->helper('core');
    
    $pager = $this->getLayout()->getBlock('featured_products_pager');
    $pager->setCollection($_productCollection);
    $_productCollection->clear();
    $_productCollection->load();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getChildHtml('featured_products_pager') ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>                    
                    <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>  
                    <?php endif; ?>
                    
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="desc std">
                  <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                </div>
                
                <?php 
                	$_specialPrice = $_product->getSpecialPrice();
                	$_price = $_product->getPrice();
                ?>
                <?php if($_specialPrice && $_specialPrice < $_price): ?>
                   <span class="old-price"><?php echo $_coreHelper->formatPrice($_price);?></span>
                   <span class="new-price">AUD <?php echo $_coreHelper->formatPrice($_specialPrice);?></span>
					 <?php $_save = $_price - $_specialPrice; ?>
					    <p class="special-price yousave">
					        <span class="label"><?php echo $this->__('You Save:') ?></span>
					        <span class="price">
					            AUD <?php echo $_coreHelper->formatPrice($_save); ?>
					        </span>
					    </p>
					 <?php else:?>
					    <span class="new-price">AUD <?php echo $_coreHelper->formatPrice($_price);?></span>
					 <?php endif; ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div>
<?php endif; ?>
