<?php
		$categories = $param = Mage::app()->getRequest()->getParam('cat'); // category ids

        $productIds = array();

        $adapter = Mage::getSingleton('core/resource')->getConnection('core_read');
        $select = $adapter->select()
                          ->from('catalog_category_product', 'catalog_category_product.product_id')
                          ->where('catalog_category_product.category_id IN (?)', $categories)
                          ->group('catalog_category_product.product_id');
        $productIds = $adapter->fetchAll($select);
        
        $product = Mage::getModel('catalog/product');
        $collection = $product->getCollection()->addAttributeToFilter('entity_id', array('in'=>$productIds));
?>

<div><?php echo $param; ?></div>

<?php
foreach ($collection as $product) {
?>

<li class="prod-list" style="width:23%;float:left;list-style:none;margin-right:16px;">
				<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(212); ?>" alt=""/>
				<h2><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($product->getName()); ?>"><?php echo $this->htmlEscape($product->getName()); ?></a></h2>
				<div id="prod-price">
					<div class="price-box">
					<?php
						$regular = Mage::helper('tax')->getPrice($product, $product->getPrice(), 2);
						$special = Mage::helper('tax')->getPrice($product, $product->getFinalPrice(), 2);
						$diff = $regular - $special;
					?>
					<div class="left">
					<?php if($regular != $special) { ?><span style="text-decoration:line-through;">$<?php echo $regular; ?></span> <?php } ?>
					<br/>
					AUD $<?php echo $special; ?>
					</div>
					<div class="right">
						<?php
						if($diff == 0) {
							echo '';
						}
						else { ?>
						you save <br/>
						AUD $<?php echo $diff; ?>
						<?php } ?>
					</div>
					</div>
				</div>
				<div>
					<a id="prod-link" href="<?php echo $product->getProductUrl(); ?>">+ Info</a>
					<?php if($product->isSaleable()): ?>
						<button type="button" id="addToCart" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::getUrl('checkout/cart/add'); ?><?php echo '?product='.$product->getId().'&qty=1'; ?>')"><?php echo $this->__('Add to Cart') ?></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></p>
                    <?php endif; ?>
					
				</div>
</li>

<?php } ?>