<h1>New Products</h1>
<?php

$collection = Mage::getModel('catalog/category')->load()
->getProductCollection()
->addAttributeToSelect('*')
->setOrder('created_at', 'desc')->setPageSize(8);
$total = $collection->getSize();
?>
<?php
foreach ($collection as $product) {
?>

<li class="prod-list" style="width:23%;float:left;list-style:none;margin-right:16px;">
				<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(212); ?>" alt=""/>
				<h2><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($product->getName()); ?>"><?php echo $this->htmlEscape($product->getName()); ?></a></h2>
				<div id="prod-price">
					<div class="price-box">
					<?php
						$regular = Mage::helper('tax')->getPrice($product, $product->getPrice(), 2);
						$special = Mage::helper('tax')->getPrice($product, $product->getFinalPrice(), 2);
						$diff = $regular - $special;
					?>
					<div class="left">
					<?php if($regular != $special) { ?><span style="text-decoration:line-through;">$<?php echo $regular; ?></span> <?php } ?>
					<br/>
					<?php if($diff == 0) { echo 'AUD $'.$regular; } else { ?> AUD $<?php echo $special; }?>
					</div>
					<div class="right">
						<?php
						if($diff == 0) {
							echo '';
						}
						else { ?>
						you save <br/>
						AUD $<?php echo $diff; ?>
						<?php } ?>
					</div>
					</div>
				</div>
				<div>
					<a id="prod-link" href="<?php echo $product->getProductUrl(); ?>">+ Info</a>
					<?php if($product->isSaleable()): ?>
						<a id="addToCart" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" href="<?php echo Mage::getUrl('checkout/cart/add'); ?><?php echo '?product='.$product->getId().'&qty=1'; ?>')"><?php echo $this->__('Add to Cart') ?></a>
                    <?php else: ?>
                        <a id="addToCart" title="<?php echo $this->__('Out of Stock') ?>" class="button btn-cart" href="#"><?php echo $this->__('Out of Stock') ?></a>
                    <?php endif; ?>
					
				</div>
</li>

<?php } ?>