		<?php
		// some helpers
		/*$_helper = $this->helper('catalog/output');
		$storeId = Mage::app()->getStore()->getId();
		$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

		// get all products that are marked as featured
		$collection = Mage::getModel('catalog/product')->getCollection();
		$collection->addAttributeToSelect('featured_product');
		$collection->addFieldToFilter(array(
			array('attribute' => 'special_product', 'eq' => true),
		));
		$collection->setPageSize(8);

		// if no products are currently featured, display some text
		if (!$collection->count()) :*/


$collection = Mage::getModel('catalog/category')->load(2)
->getProductCollection()
->addAttributeToSelect('*')
->setOrder('created_at', 'desc')->setPageSize(5);
$total = $collection->getSize();
?>
	

<div id="feature_list">
	
			<ul id="tabs">
			<?php
				foreach ($collection as $product) :
			?>
				<li>
					<a href="javascript:;">
						<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(22); ?>" />
						<h3><?php echo $this->htmlEscape($product->getName()); ?></h3>
					</a>
				</li>
			<?php endforeach; ?>
			</ul>
			<ul id="output">
			<?php
				foreach ($collection as $product) :
			?>
				<li>
					<h3><?php echo $this->htmlEscape($product->getName()); ?></h3>
					<img src="<?php echo $this->getSkinUrl('images/banner.jpg') ?>" alt="banner" />
					<a href="<?php echo $product->getProductUrl(); ?>">Click Here</a>
				</li>
			<?php
				endforeach;
			?>
			</ul>

</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.featureList-1.0.0.js'); ?>"></script>
	<style type="text/css">
	
		div#feature_list {
			width: 1024px;
			height: 360px;
			overflow: hidden;
			position: relative;
		}

		div#feature_list ul {
			position: absolute;
			top: 0;
			list-style: none;	
			padding: 0;
			margin: 0;
		}

		ul#tabs {
			left: 0;
			z-index: 2;
			width: 320px;
			background:rgba(25,25,25,.8);
		}

		ul#tabs h3 {
			color:white;
			font-size:15px;
			padding-top:8px;
		}
		
		ul#tabs li {
			font-size: 12px;
			font-family: Arial;
		}
		
		ul#tabs li img {
			padding: 5px;
			border: none;
			float: left;
			margin: 10px 10px 0 0;
		}

		ul#tabs li a {
			color: #222;
			text-decoration: none;	
			display: block;
			padding: 10px;
			height: 52px;
			outline: none;
		}

		ul#tabs li a:hover {
			text-decoration: underline;
		}

		ul#tabs li a.current {
			background:  rgba(20,60,20,.75);
			color: #FFF;
			background: rgb(31,79,50); /* Old browsers */
			background: -moz-linear-gradient(top,  rgba(31,79,50,1) 0%, rgba(18,63,21,1) 100%); /* FF3.6+ */
			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(31,79,50,1)), color-stop(100%,rgba(18,63,21,1))); /* Chrome,Safari4+ */
			background: -webkit-linear-gradient(top,  rgba(31,79,50,1) 0%,rgba(18,63,21,1) 100%); /* Chrome10+,Safari5.1+ */
			background: -o-linear-gradient(top,  rgba(31,79,50,1) 0%,rgba(18,63,21,1) 100%); /* Opera 11.10+ */
			background: -ms-linear-gradient(top,  rgba(31,79,50,1) 0%,rgba(18,63,21,1) 100%); /* IE10+ */
			background: linear-gradient(to bottom,  rgba(31,79,50,1) 0%,rgba(18,63,21,1) 100%); /* W3C */
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1f4f32', endColorstr='#123f15',GradientType=0 ); /* IE6-9 */

		}

		ul#tabs li a.current:hover {
			text-decoration: none;
			cursor: default;
		}

		ul#output {
			right: 0;
			width: 1024px;
			height: 360px;
			position: relative;
		}

		ul#output li {
			position: absolute;
			width: 1024px;
			height: 360px;
		}
		
		ul#output li h3 {
			position:absolute;
			left:340px;
			top:12px;
			width:auto;
			height:auto;
			font-size:22px;
			color:white;
			text-transform:uppercase;
			font-weight:bold;
			text-shadow:0px 0px 4px #000;
		}

		ul#output li a {
			background: url('<?php echo $this->getSkinUrl('images/click.jpg') ?>') no-repeat;
			bottom: 25px;
			box-shadow: 0 0 12px #000000;
			color: #FFFFFF;
			font-size: 35px;
			left: 360px;
			padding: 8px 40px;
			position: absolute;
			text-decoration: none;
		}
		
		ul#output li a:hover {
			background: #123f15;
		}
	</style>
	<script language="javascript">
		var jqr = jQuery.noConflict();
		
		jqr(document).ready(function($) {

			$.featureList(
				$("#tabs li a"),
				$("#output li"), {
					start_item	:	1
				}
			);

			/*
			
			// Alternative

			
			$('#tabs li a').featureList({
				output			:	'#output li',
				start_item		:	1
			});

			*/

		});
	</script>