<div class="block block-layered-nav">	
	<div class="block-content">
        <dl id="sort-by-size">
            <dt class="last odd">Size <button class="right" type="">Clear</button></dt>
				<div class="left">
					<input type="checkbox" name="size" value="s"/><label>S</label>
				</div>
				<div class="left">
					<input type="checkbox" name="size" value="m"/><label>M</label>
				</div>
				<div class="left">
					<input type="checkbox" name="size" value="l"/><label>L</label>
				</div>
				<div class="left">
					<input type="checkbox" name="size" value="xl"/><label>XL</label>
				</div>
				<div class="left">
					<input type="checkbox" name="size" value="xxl"/><label>XXL</label>
				</div>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
	</div>
</div>